server:
  port: 11520

wechat:
  appid: x
  secret: x
  get-access-token-url: https://api.weixin.qq.com/cgi-bin/token
  get-user-list: https://api.weixin.qq.com/cgi-bin/user/get
  send-template-msg-url: https://api.weixin.qq.com/cgi-bin/message/template/send
  drink-water-template-id: x

