server:
  port: 11520

#微信
wechat:
  appid: x
  secret: x
  get-access-token-url: https://api.weixin.qq.com/cgi-bin/token
  get-user-list: https://api.weixin.qq.com/cgi-bin/user/get
  send-template-msg-url: https://api.weixin.qq.com/cgi-bin/message/template/send
  drink-water-template-id: EMPW5c36TqqWJSp_2gArp9Fusrvu1Bbv1lxhpK0bW4w
  zaoan-template-id: rAEnMXsA9ooVAK4jcTSI696cWkXkxnS-nNq5h2P7tl4
  xiaban-template-id: MmPo3Mw98BDs51cKWVvDsw_zq3qMZv82ndo9JlR010g
  wanan-template-id: nkFrQY1d4F7gVbrUVA1sMlWXyZRdCUCQ9B3YU8BErvI

#高德
amap:
  key: x
  city: x
  weather-url: https://restapi.amap.com/v3/weather/weatherInfo

#天行
tian:
  key: x
  dujitang-url: https://apis.tianapi.com/dujitang/index
  zaoan-url: https://apis.tianapi.com/zaoan/index
  wanan-url: https://apis.tianapi.com/wanan/index
  one-url: https://apis.tianapi.com/one/index

